version: "3"
services:
  chat:
    build: .
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: "redis:6.0"
    restart: always
