version: "3"
services:
  redis:
    image: "redis:5.0-rc3"
    restart: always
  chat:
    build: .
    command: npm start
    volumes:
      - .:/myapp
      - /myapp/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - redis
